version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'urlApp'
      MYSQL_PASSWORD: '1234'
      MYSQL_DATABASE: 'shortner'
    ports:
      - "3306:3306"